CREATE TABLE TRANSACTION (
  TXN_ID VARCHAR(64) PRIMARY KEY,
  TXN_TYPE VARCHAR(20),
  AMOUNT DECIMAL(18,2),
  CURRENCY VARCHAR(10),
  SOURCE_SYSTEM VARCHAR(50)
);

CREATE TABLE TRANSACTION_DETAILS (
  TXN_ID VARCHAR(64),
  CUSTOMER_ID VARCHAR(64),
  CHANNEL VARCHAR(50)
);

CREATE TABLE TRANSACTION_ADDRESS (
  ADDRESS_ID VARCHAR(64),
  TXN_ID VARCHAR(64),
  ADDRESS_TYPE VARCHAR(20),
  LINE1 VARCHAR(255),
  CITY VARCHAR(100),
  COUNTRY VARCHAR(50)
);
